apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-sentry
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-sentry
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list"]
  # Allow fetching pods information to add more information to issues
  - apiGroups: [""]
    resource: ["pods"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-sentry
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-sentry
subjects:
  - kind: ServiceAccount
    name: k8s-sentry
